name: Demo

on: [push]

jobs:
  run-commands:
    runs-on: windows-latest
    steps:
      - name: echo string
        run: echo "Hello Second World"
      - name: Directory Powershell
        run: Get-Location
  run-second-command:
    runs-on: ubuntu-latest
    needs: ["run-commands"]
    steps: 
      - name: echo "second string"
        run: echo "Hello Mars"
      - name: python "run-commands"
        run: |
         import platform
         print(platform.processor())
         shell: python
        

