name: Demo

on: [push]

jobs:
  run-commands:
    runs-on: windows-latest
    steps:
      - name: echo string
        run: echo "Hello Second World"
      - name: Directory Powershell
        run: Get-Location
  run-second-command:
    runs-on: ubuntu-latest
    needs: ["run-commands"]
    env:
      OWNER_NAME: 'Ankit Bisht'
    steps: 
      - name: echo "second string"
        run: echo "Hello Mars"
      - name: echo owner name
        run: echo ${OWNER_NAME}
    
        

