name: Demo

on: [push]

jobs:
  run-commands:
    runs-on: windows-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: Directory Powershell
        run: Get-Location
        

